version: '2'
services:
  fake-smtp:
    build:
      context: .
      dockerfile: containers/fake-smtp/Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    ports:
      - "8080:8080"
      - "2525:2525"
    volumes:
      - ./data/smtp:/fake-smtp/data/smtp
  fake-ldap:
    build:
      context: .
      dockerfile: containers/fake-ldap/Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    ports:
      - "8081:8081"
      - "3389:3389"
    volumes:
      - ./data/ldap:/fake-ldap/data/ldap
  fake-cas:
    build:
      context: .
      dockerfile: containers/fake-cas/Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    ports:
      - "8443:8443"
    volumes:
      - ./data/cas:/fake-cas/data/cas
