version: '2'
services:
  faketools:
    build:
      context: .
      dockerfile: containers/faketools/Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    ports:
      - "${SMTP_APP_PORT}:8080"
      - "${LDAP_APP_PORT}:8081"
      - "${SMTP_PORT}:2525"
      - "${LDAP_PORT}:3389"
      - "${CAS_PORT}:8443"
      - "${SFTP_PORT}:22"
    volumes:
      - ./data:/faketools/data
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
