version: '2'
services:
  faketools:
    build:
      context: .
      dockerfile: containers/faketools/Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    ports:
      - "8080:8080"
      - "8081:8081"
      - "2525:2525"
      - "3389:3389"
      - "8443:8443"
      - "2222:22"
    volumes:
      - ./data:/faketools/data
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
